ROWS = 15
COLS = 15
TILE_SIZE = 48
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 90
HEALTH = 100
MONEY = 650
TOTAL_LEVELS = 15

# enemy constants
SPAWN_COOLDOWN = 400

# turret constants
TURRET_LEVELS = 4
BUY_COST = 200
UPGRADE_COST = 100
KILL_REWARD = 5
LEVEL_COMPLETE_REWARD = 100
ANIMATION_STEPS = 8
ANIMATION_DELAY = 10
DAMAGE = 5
